config/routes.rb
require 'can_access_admin'

Rails.application.routes.draw do

  get '/feeds/simply-hired', to: 'feeds#simply_hired'
  get '/feeds/indeed-fr', to: 'feeds#indeed_fr'
  get '/feeds/wanajob', to: 'feeds#wanajob'
  get '/feeds/les-offres-emplois-fr', to: 'feeds#les_offres_emplois_fr'
  get '/feeds/trovit', to: 'feeds#trovit'

  root 'application#index'

    ResqueWeb::Engine.eager_load!
    mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do
      get '/users/is_email_free', to: 'users#check_email_is_free'
      post '/users/change_email', to: 'users#change_email'
      get '/users/request_password', to: 'users#request_password'
      put '/users/change_password', to: 'users#change_password'
      resources :users
      resources :professions
      resources :post_categories
      resources :places
      resources :classified_ads
      resources :professionals
      resources :tags
      get '/transactions/generate_invoice', to: 'transactions#generate_invoice'
      resources :transactions
      resources :quotation_requests
      resources :conversations
      resources :authorizations
      resources :deals
      resources :referrals do
        get :list, on: :collection
      end
      resources :sessions, only: [:create, :destroy]
      resources :pricings
      resources :quotation_request_templates
      resources :users_favorite_professionals, only: [:create, :destroy, :index]
      resources :users_favorite_posts, only: [:create, :destroy, :index]
      resources :users_favorite_post_comments, only: [:create, :destroy]
      resources :users_favorite_deals, only: [:create, :destroy, :index]
      resources :users_favorites, only: [:index]
      resources :pro_ratings
      resources :pro_reviews
      resources :profile_sponsorings
      resources :posts
      resources :post_category_subscriptions, only: [:create, :destroy]
      resources :post_author_subscriptions, only: [:create, :destroy]
      resources :post_comments, only: [:create, :index]
      get '/departements', to: 'places#departements'
      get '/user_notifications', to: 'users#get_notifications'
      get '/user_possible_nickname', to: 'users#get_possible_nickname'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :users do
      member do
        post :add_credits
        post :subtract_credits
      end
    end
    resources :posts
    resources :professions
    resources :classified_ads
    resources :pricings
    resources :price_for_categories
    resources :deals
    resources :reviews
    resources :posts
    resources :post_comments
    resources :post_categories
  end

  resources :pros, path: '/pro', only: [:show]
  resources :posts, path: '/post', only: [:show]

  post '/payments/notify', to: 'payments#notify'
  get '/payments/cancel', to: 'payments#cancel'

  get '/images/:geometry' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid]).thumb(params[:geometry])
  }

  get '/images/' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid])
  }

  match "/websocket", to: WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get "*path.html" => "application#index", :layout => 0
  get '*path' => 'application#index'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

  def index
    @user_count = User.where.not(first_login: nil).count
    @active_user_count = User.with_active_state.count
    # @active_user_count = User.where('last_login >= ?', Date.today - 30).count

    @profession_count = Profession.all.count
    @active_profession_count = Profession.where(active: true).count

    @classified_ad_count = ClassifiedAd.all.count
    @published_classified_ad_count = ClassifiedAd.with_published_state.count

    @post_count = Post.all.count
    @published_post_count = Post.with_published_state.count

    @post_category_count = PostCategory.all.count
    @active_post_count = PostCategory.where(active: true).count
  end

end

app/views/admin/dashboard/index.html.haml
.page-header
  %h1 Admin dashboard

.row
  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Utilisateurs
      .panel-body
        .row
          .col-xs-6 Total
          .col-xs-6.text-right
            %strong= @user_count
        .row
          .col-xs-6 Actifs
          .col-xs-6.text-right
            %strong= @active_user_count
        %p
        = link_to 'Voir tous les utilisateurs', admin_users_path, class: 'btn btn-primary btn-lg btn-block'

  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Professions
      .panel-body
        .row
          .col-xs-6 Total
          .col-xs-6.text-right
            %strong= @profession_count
        .row
          .col-xs-6 Actives
          .col-xs-6.text-right
            %strong= @active_profession_count
        %p
        = link_to 'Voir toutes les professions', admin_professions_path, class: 'btn btn-primary btn-lg btn-block'

  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Annonces
      .panel-body
        .row
          .col-xs-6 Total
          .col-xs-6.text-right
            %strong= @classified_ad_count
        .row
          .col-xs-6 Ouvertes
          .col-xs-6.text-right
            %strong= @published_classified_ad_count
        %p
        = link_to 'Voir toutes les annonces', admin_classified_ads_path, class: 'btn btn-primary btn-lg btn-block'

.row
  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Posts
      .panel-body
        .row
          .col-xs-6 Total
          .col-xs-6.text-right
            %strong= @post_count
        .row
          .col-xs-6 Publiés
          .col-xs-6.text-right
            %strong= @published_post_count
        %p
        = link_to 'Voir tous les posts', admin_posts_path, class: 'btn btn-primary btn-lg btn-block'

  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Catégories des posts
      .panel-body
        .row
          .col-xs-6 Total
          .col-xs-6.text-right
            %strong= @post_category_count
        .row
          .col-xs-6 Actives
          .col-xs-6.text-right
            %strong= @active_post_count
        %p
        = link_to 'Voir toutes les catégories', admin_post_categories_path, class: 'btn btn-primary btn-lg btn-block'