config/routes.rb
require 'can_access_admin'

Rails.application.routes.draw do

  get '/feeds/simply-hired', to: 'feeds#simply_hired'
  get '/feeds/indeed-fr', to: 'feeds#indeed_fr'
  get '/feeds/wanajob', to: 'feeds#wanajob'
  get '/feeds/les-offres-emplois-fr', to: 'feeds#les_offres_emplois_fr'
  get '/feeds/trovit', to: 'feeds#trovit'

  root 'application#index'

    ResqueWeb::Engine.eager_load!
    mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do
      get '/users/is_email_free', to: 'users#check_email_is_free'
      post '/users/change_email', to: 'users#change_email'
      get '/users/request_password', to: 'users#request_password'
      put '/users/change_password', to: 'users#change_password'
      resources :users
      resources :professions
      resources :post_categories
      resources :places
      resources :classified_ads
      resources :professionals
      resources :tags
      get '/transactions/generate_invoice', to: 'transactions#generate_invoice'
      resources :transactions
      resources :quotation_requests
      resources :conversations
      resources :authorizations
      resources :deals
      resources :referrals do
        get :list, on: :collection
      end
      resources :sessions, only: [:create, :destroy]
      resources :pricings
      resources :quotation_request_templates
      resources :users_favorite_professionals, only: [:create, :destroy, :index]
      resources :users_favorite_posts, only: [:create, :destroy, :index]
      resources :users_favorite_post_comments, only: [:create, :destroy]
      resources :users_favorite_deals, only: [:create, :destroy, :index]
      resources :users_favorites, only: [:index]
      resources :pro_ratings
      resources :pro_reviews
      resources :profile_sponsorings
      resources :posts
      resources :post_category_subscriptions, only: [:create, :destroy]
      resources :post_author_subscriptions, only: [:create, :destroy]
      resources :post_comments, only: [:create, :index]
      get '/departements', to: 'places#departements'
      get '/user_notifications', to: 'users#get_notifications'
      get '/user_possible_nickname', to: 'users#get_possible_nickname'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :users do
      member do
        post :add_credits
        post :subtract_credits
      end
    end
    resources :posts
    resources :professions
    resources :classified_ads
    resources :pricings
    resources :price_for_categories
    resources :deals
    resources :reviews
    resources :posts
    resources :post_comments
    resources :post_categories
  end

  resources :pros, path: '/pro', only: [:show]
  resources :posts, path: '/post', only: [:show]

  post '/payments/notify', to: 'payments#notify'
  get '/payments/cancel', to: 'payments#cancel'

  get '/images/:geometry' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid]).thumb(params[:geometry])
  }

  get '/images/' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid])
  }

  match "/websocket", to: WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get "*path.html" => "application#index", :layout => 0
  get '*path' => 'application#index'

end

app/models/pricing.rb
# == Schema Information
#
# Table name: pricings
#
#  id         :integer          not null, primary key
#  target     :string(255)
#  start_date :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Pricing < ActiveRecord::Base
	validates :start_date, presence: true
	validates :target, presence: true

	has_many :price_for_categories
	has_many :pricing_categories, through: :price_for_categories

	def self.active(target)
		where(target: target).where("start_date <= NOW()").order(start_date: :desc).first
	end

	def active?
		start_date <= Date.today && Pricing.where(target: target).where("start_date <= NOW() && start_date > ?", start_date).count == 0 && pricing_categories.count == PricingCategory.all.count
	end
end

app/controllers/admin/pricings_controller.rb
class Admin::PricingsController < AdminController

  def index
    @pricings = Pricing.order(start_date: :desc)
  end

  def edit
    @pricing = Pricing.find(params[:id])
  end

  def update
    @pricing = Pricing.find(params[:id])
    if @pricing.update_attributes(pricing_params)
      flash[:notice] = "Prix pour #{@pricing.target} modifié"
      redirect_to admin_pricings_path
    else
      flash[:alert] = "La modification du prix a échoué"
      render :edit
    end
  end

  def new
    @pricing = Pricing.new
  end

  def create
    @pricing = Pricing.new(pricing_params)
    if @pricing.save
      flash[:notice] = "Prix ajouté pour #{@pricing.target}"
      redirect_to admin_pricings_path
    else
      flash[:alert] = "L'ajout du prix a échoué"
      render :new
    end
  end

  private

  def pricing_params
    params.require(:pricing).permit(:target, :start_date)
  end

end

app/controllers/api/v1/pricings_controller.rb
class Api::V1::PricingsController < ApiController
	def index
		if signed_in?
      if params.has_key?(:deals)
        pricings = Pricing.where("target LIKE 'deal_%'").select { |pricing| pricing.active? }
      elsif params.has_key?(:fleches)
        pricings = Pricing.where("target IN ('forfait_1', 'forfait_2', 'forfait_3', 'forfait_4', 'change_rate')").select { |pricing| pricing.active? }
      elsif params.has_key?(:profile)
        pricings = Pricing.where("target IN ('sponsored_profile', 'sponsored_map_profile')").select { |pricing| pricing.active? }
      elsif params.has_key?(:posts)
        pricings = Pricing.where("target IN ('sponsored_post')").select { |pricing| pricing.active? }
      else
        pricings = Pricing.select { |pricing| pricing.active? }
      end
      render json: pricings, status: :ok
		else
			render json: nil, status: :unauthorized
		end
	end

  def show
    if signed_in?
      pricing = Pricing.active(params[:id])
      if pricing.present?
        render json: pricing, status: :ok
      else
        render json: nil, status: :not_found
      end
    else
      render json: nil, status: :unauthorized
    end
  end

end

app/views/admin/pricings/_form.html.haml
.row
  .col-sm-12

    = form_for [:admin, @pricing] do |f|

      .form-group
        %label Type
        = f.select(:target, [ ['Forfait 1', 'forfait_1'], ['Forfait 2', 'forfait_2'], ['Forfait 3', 'forfait_3'], ['Forfait 4', 'forfait_4'], ['Taux de change', 'change_rate'], ["Visibilité Bon plan - Page d'accueil", 'deal_homepage'], ["Visibilité Bon Plan - Bons plans sponsorisés sur page BP", 'deal_deals'], ["Visibilité Bon plan - Sur carte", 'deal_map'], ["Visibilité Bon plan - Plus d'adresses", 'deal_more_addresses'], ['Visibilité Profil - Profil sponsorisé', 'sponsored_profile'], ['Visibilité Profil - Profil ouvert sur carte', 'sponsored_map_profile'], ['Ouvrir une annonce', 'classified_ad_unlock'], ["Points offerts à l'inscription", 'bonus_signup'], ["Points offerts pour parrainage", 'bonus_referral'], ['Visibilité Post - Post sponsorisé', 'sponsored_post'] ], include_blank: true, required: true)

      .form-group
        %label Date de début
        = f.date_field :start_date, min: Date.today, required: true, class: "form-control"

      = f.submit "Enregistrer", class: "btn btn-primary"

app/views/admin/pricings/_pricings_table.html.haml
.table-responsive  
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th Type
        %th Date de début
        %th Actif
        %th Action
    %tbody
      - @pricings.each do |p|
        %tr
          %td= p.id
          %td= p.target
          %td= p.start_date
          %td
            - if p.active?
              %span.glyphicon.glyphicon-ok
          %td
            = link_to "Modifier", edit_admin_pricing_path(p), class: "btn btn-default btn-xs"
            = link_to "Ajouter un prix", new_admin_price_for_category_path(pricing_id: p.id), class: "btn btn-default btn-xs"

app/views/admin/pricings/edit.html.haml
.page-header
	%h1
		Modifier le prix pour
		= @pricing.target

= render partial:'form'

app/views/admin/pricings/index.html.haml
.page-header
	%h1 Types de prix

	%p.pull-right= link_to "Ajouter un type de prix", new_admin_pricing_path, class: "btn btn-primary btn-xs"

= render partial:'admin/pricings/pricings_table', locals: {pricings: @pricings}

app/views/admin/pricings/new.html.haml
.page-header
  %h1 Ajouter un prix

= render partial:'form'