config/routes.rb
require 'can_access_admin'

Rails.application.routes.draw do

  get '/feeds/simply-hired', to: 'feeds#simply_hired'
  get '/feeds/indeed-fr', to: 'feeds#indeed_fr'
  get '/feeds/wanajob', to: 'feeds#wanajob'
  get '/feeds/les-offres-emplois-fr', to: 'feeds#les_offres_emplois_fr'
  get '/feeds/trovit', to: 'feeds#trovit'

  root 'application#index'

    ResqueWeb::Engine.eager_load!
    mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do
      get '/users/is_email_free', to: 'users#check_email_is_free'
      post '/users/change_email', to: 'users#change_email'
      get '/users/request_password', to: 'users#request_password'
      put '/users/change_password', to: 'users#change_password'
      resources :users
      resources :professions
      resources :post_categories
      resources :places
      resources :classified_ads
      resources :professionals
      resources :tags
      get '/transactions/generate_invoice', to: 'transactions#generate_invoice'
      resources :transactions
      resources :quotation_requests
      resources :conversations
      resources :authorizations
      resources :deals
      resources :referrals do
        get :list, on: :collection
      end
      resources :sessions, only: [:create, :destroy]
      resources :pricings
      resources :quotation_request_templates
      resources :users_favorite_professionals, only: [:create, :destroy, :index]
      resources :users_favorite_posts, only: [:create, :destroy, :index]
      resources :users_favorite_post_comments, only: [:create, :destroy]
      resources :users_favorite_deals, only: [:create, :destroy, :index]
      resources :users_favorites, only: [:index]
      resources :pro_ratings
      resources :pro_reviews
      resources :profile_sponsorings
      resources :posts
      resources :post_category_subscriptions, only: [:create, :destroy]
      resources :post_author_subscriptions, only: [:create, :destroy]
      resources :post_comments, only: [:create, :index]
      get '/departements', to: 'places#departements'
      get '/user_notifications', to: 'users#get_notifications'
      get '/user_possible_nickname', to: 'users#get_possible_nickname'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :users do
      member do
        post :add_credits
        post :subtract_credits
      end
    end
    resources :posts
    resources :professions
    resources :classified_ads
    resources :pricings
    resources :price_for_categories
    resources :deals
    resources :reviews
    resources :posts
    resources :post_comments
    resources :post_categories
  end

  resources :pros, path: '/pro', only: [:show]
  resources :posts, path: '/post', only: [:show]

  post '/payments/notify', to: 'payments#notify'
  get '/payments/cancel', to: 'payments#cancel'

  get '/images/:geometry' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid]).thumb(params[:geometry])
  }

  get '/images/' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid])
  }

  match "/websocket", to: WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get "*path.html" => "application#index", :layout => 0
  get '*path' => 'application#index'

end

app/models/email_template.rb
class EmailTemplate < ActiveRecord::Base

	validates :name, presence: true, length: { minimum: 3, maximum: 250 }
  validates :subject, presence: true, length: { minimum: 3, maximum: 250 }, on: :update
  validates :body, presence: true, on: :update


def deliver_to(to, options = {})
    prms = {
      to: to,
      subject: subject,
      body: body,
      content_type: "text/html"
    }
    prms.merge!( options.delete_if{ |k, v| v.blank? })
    ApplicationMailer.mail( prms ) do |f|
      f.html
    end.deliver
  end
end

app/controllers/admin/email_templates_controller.rb
class Admin::EmailTemplatesController < AdminController
	before_filter :set_template, only: [:show, :edit, :destroy,:update]

	def index
		@templates = EmailTemplate.order(created_at: :desc)
	end

	def edit
	end

	def show
	end

	def update
		if @template.update_attributes(template_params)
			flash[:notice] = "Email template #{params[:id]} update successfully"	
			redirect_to admin_email_templates_path
		else
			render :edit, error: @template.errors.full_messages
		end
	end

  def destroy
    @template.destroy
    flash[:notice] = "Email template #{params[:id]} supprimé"
    redirect_to admin_email_templates_path
  end

  private 

  def set_template
  	@template = EmailTemplate.find(params[:id])
  end

  def template_params
  	params.require(:email_template).permit(:name,:subject,:body)
  end
end

app/views/admin/email_templates/edit.html.haml
.page-header
  %h1
    Modifier la template 
    = @template.name
.row
  .col-sm-12

    = form_for [:admin, @template] do |f|

      .form-group
        %label Nom
        = f.text_field :name, class: "form-control"

      .form-group
        %label Subject
        = f.text_field :subject, class: "form-control"

      .form-group
        %label Body
        = f.text_area :body, size: "60x10", class: "form-control"

      .checkbox
        %label
          = f.check_box :active
          Actif

      = f.submit "Enregistrer", class: "btn btn-primary"

app/views/admin/email_templates/index.html.haml
.page-header
  %h1= t('admin.email_templates')
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th name
        %th subject
        %th body
        %th created at
    %tbody
      - @templates.each do |template|
        %tr
          %td= template.id
          %td= template.name
          %td= template.subject[0..50]
          %td= raw template.body
          %td= template.created_at
          %td
            = link_to "Modifier", edit_admin_email_template_path(template), class: "btn btn-default btn-xs"
          %td
            = link_to admin_email_template_path(template), class: 'btn btn-danger btn-xs', method: :delete, title: "Supprimer template #{template.id}", data: {confirm: "Vous allez supprimer le template #{template.id}. Etes-vous sûr ?"} do
              %i.fa.fa-times

app/views/admin/email_templates/show.html.haml
.page-header
  %h1
    = "Pro review ##{@review.id}"
  = link_to admin_review_path(@review), class: 'btn btn-danger btn-xs', method: :delete, title: "Supprimer bon plan #{@review.id}", data: {confirm: "Vous allez supprimer le bon plan #{@review.id}. Etes-vous sûr ?"} do
    %i.fa.fa-times
.row
  .col-sm-12
    .row
      .col-sm-3
        %strong Content
      .col-sm-9= @review.content
    .row
      .col-sm-3
        %strong Rating
      .col-sm-9
        %span= review_rating(@review.rating)
    .row
      .col-sm-3
        %strong Date
      .col-sm-9= @review.created_at
    .row
      .col-sm-3
        %strong User
      .col-sm-9
        = link_to admin_user_path(@review.user), class: "btn btn-default btn-xs" do
          = image_tag @review.user.avatar.thumb('20x20').url, style: "width: 20px; height:20px;" if @review.user.avatar_stored?
          = @review.user.display_name
    .row
      .col-sm-3
        %strong Professional
      .col-sm-9
        = link_to admin_user_path(@review.professional), class: "btn btn-default btn-xs" do
          = image_tag @review.professional.avatar.thumb('20x20').url, style: "width: 20px; height:20px;" if @review.professional.avatar_stored?
          = @review.professional.display_name
    .row
      .col-sm-6
        = link_to "Back",:back,class: "btn btn-primary btn-xs"