config/routes.rb
require 'can_access_admin'

Rails.application.routes.draw do

  get '/feeds/simply-hired', to: 'feeds#simply_hired'
  get '/feeds/indeed-fr', to: 'feeds#indeed_fr'
  get '/feeds/wanajob', to: 'feeds#wanajob'
  get '/feeds/les-offres-emplois-fr', to: 'feeds#les_offres_emplois_fr'
  get '/feeds/trovit', to: 'feeds#trovit'

  root 'application#index'

    ResqueWeb::Engine.eager_load!
    mount ResqueWeb::Engine => "/resque"

  namespace :api do
    namespace :v1 do
      get '/users/is_email_free', to: 'users#check_email_is_free'
      post '/users/change_email', to: 'users#change_email'
      get '/users/request_password', to: 'users#request_password'
      put '/users/change_password', to: 'users#change_password'
      resources :users
      resources :professions
      resources :post_categories
      resources :places
      resources :classified_ads
      resources :professionals
      resources :tags
      get '/transactions/generate_invoice', to: 'transactions#generate_invoice'
      resources :transactions
      resources :quotation_requests
      resources :conversations
      resources :authorizations
      resources :deals
      resources :referrals do
        get :list, on: :collection
      end
      resources :sessions, only: [:create, :destroy]
      resources :pricings
      resources :quotation_request_templates
      resources :users_favorite_professionals, only: [:create, :destroy, :index]
      resources :users_favorite_posts, only: [:create, :destroy, :index]
      resources :users_favorite_post_comments, only: [:create, :destroy]
      resources :users_favorite_deals, only: [:create, :destroy, :index]
      resources :users_favorites, only: [:index]
      resources :pro_ratings
      resources :pro_reviews
      resources :profile_sponsorings
      resources :posts
      resources :post_category_subscriptions, only: [:create, :destroy]
      resources :post_author_subscriptions, only: [:create, :destroy]
      resources :post_comments, only: [:create, :index]
      get '/departements', to: 'places#departements'
      get '/user_notifications', to: 'users#get_notifications'
      get '/user_possible_nickname', to: 'users#get_possible_nickname'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :users do
      member do
        post :add_credits
        post :subtract_credits
      end
    end
    resources :posts
    resources :professions
    resources :classified_ads
    resources :pricings
    resources :price_for_categories
    resources :deals
    resources :reviews
    resources :posts
    resources :post_comments
    resources :post_categories
  end

  resources :pros, path: '/pro', only: [:show]
  resources :posts, path: '/post', only: [:show]

  post '/payments/notify', to: 'payments#notify'
  get '/payments/cancel', to: 'payments#cancel'

  get '/images/:geometry' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid]).thumb(params[:geometry])
  }

  get '/images/' => Dragonfly.app.endpoint { |params, app|
    app.fetch(params[:uid])
  }

  match "/websocket", to: WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get "*path.html" => "application#index", :layout => 0
  get '*path' => 'application#index'

end

app/models/post_comment.rb
# == Schema Information
#
# Table name: pro_comments
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  post_id     :integer
#  last_read_at    :datetime
#  unread          :boolean          default(FALSE)
#  notified        :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class PostComment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	has_many :users_favorite_post_comments, dependent: :destroy
	has_many :post_comment_user_mentions, dependent: :destroy

	def send_notifications
    self.unread = true
		if post.user != user
      if post.post_comments.where(unread: true, notified: true).count == 0
        if post.user.online
          Fiber.new do
            WebsocketRails["user_#{post.user.id}"].trigger(:post_comment_new, { post_id: post.id, post_title: post.title, from_user: user.pretty_name })
          end.resume
        else
          NotificationMailer.new_post_comment_email(user.id, post.user.id, self.id).deliver
        end
        self.notified = true
      end
    end
    self.save

    post_comment_user_mentions.each do |user_mention|
			if user_mention.user.online
        Fiber.new do
          WebsocketRails["user_#{user_mention.user.id}"].trigger(:post_comment_mention_new, { post_id: post.id, post_title: post.title, from_user: user.pretty_name })
        end.resume
      else
        NotificationMailer.new_post_comment_mention_email(user_mention.user.id, post.id).deliver
      end
      user_mention.update(notified: true, unread: true)
    end
	end

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < AdminController
	def index
		@post_comments = PostComment.all.order(created_at: :desc)
	end

	def show
		@post_comment = PostComment.find(params[:id])
	end

  def destroy
    @comment = PostComment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Commentaire #{params[:id]} supprimé"
    redirect_to admin_post_comments_path
  end
end

app/controllers/api/v1/post_comments_controller.rb
class Api::V1::PostCommentsController < ApiController

  def index
    if params.has_key?(:id) && params[:id].present?
      post = Post.find_by(slug: params[:id]) || Post.find(params[:id])
      if post.present?
        comments = PostComment.where(post: post).order(updated_at: :desc)
        render json: comments, status: :ok
      else
        render json: nil, status: :not_found
      end
    else
      render json: nil, status: :unprocessable_entity
    end
  end

	def create
    if signed_in?
      post = Post.find_by(slug: params[:post_id]) || Post.find(params[:post_id])
      if post.present? && params.has_key?(:content) && params[:content].present?
        post_comment = PostComment.new(post: post, user: current_user)
        if post_comment.update_attributes(content: params[:content])
          params[:content].scan(/@\b[a-zA-Z0-9\u00C0-\u017F\-]+/) do |mention|
            mention.delete!("@")
            user_mentioned = User.find_by_pretty_name(mention)
            if user_mentioned.present?
              begin
                post_user_mention = PostCommentUserMention.create(user: user_mentioned, post_comment: post_comment)
                post_comment.post_user_mentions << post_user_mention
              rescue
                #Already exist
              end
            end
          end
          post_comment.send_notifications
          render json: nil, status: :created
        else
          render json: post_comment.errors, status: :unprocessable_entity
        end
      else
        render json: nil, status: :unprocessable_entity
      end
    else
      render json: nil, status: :unauthorized
    end
  end

end

app/views/admin/post_comments/index.html.haml
.page-header
  %h1= t('admin.post_comment.title')
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th Contenu
        %th Date
        %th Utilisateur
        %th Post
        %th Action
    %tbody
      - @post_comments.each do |post_comment|
        %tr
          %td= post_comment.id
          %td= post_comment.content[0..50]
          %td= post_comment.created_at
          %td
            = link_to admin_user_path(post_comment.user), class: "btn btn-default btn-xs" do
              = post_comment.user.pretty_name
          %td
            = link_to admin_post_path(post_comment.post), class: "btn btn-default btn-xs" do
              = post_comment.post.title
          %td
            = link_to "Voir", admin_post_comment_path(post_comment), class: "btn btn-default btn-xs"
            = link_to admin_post_comment_path(post_comment), class: 'btn btn-danger btn-xs', method: :delete, title: "Supprimer le commentaire #{post_comment.id}", data: {confirm: "Vous allez supprimer le commentaire #{post_comment.id}. Etes-vous sûr ?"} do
              %i.fa.fa-times

app/views/admin/post_comments/show.html.haml
.page-header
  %h1
    = "Commentaire de post ##{@post_comment.id}"
  = link_to admin_post_comment_path(@post_comment), class: 'btn btn-danger btn-xs', method: :delete, title: "Supprimer le commentaire #{@post_comment.id}", data: {confirm: "Vous allez supprimer le commentaire #{@post_comment.id}. Etes-vous sûr ?"} do
    %i.fa.fa-times
.row
  .col-sm-12
    .row
      .col-sm-3
        %strong Contenu
      .col-sm-9= @post_comment.content
    .row
      .col-sm-3
        %strong Date
      .col-sm-9= @post_comment.created_at
    .row
      .col-sm-3
        %strong Utilisateur
      .col-sm-9
        = link_to admin_user_path(@post_comment.user), class: "btn btn-default btn-xs" do
          = image_tag @post_comment.user.avatar.thumb('20x20').url, style: "width: 20px; height:20px;" if @post_comment.user.avatar_stored?
          = @post_comment.user.pretty_name
    .row
      .col-sm-3
        %strong Post
      .col-sm-9
        = link_to admin_post_path(@post_comment.post), class: "btn btn-default btn-xs" do
          = @post_comment.post.title
    .row
      .col-sm-6
        = link_to "Back",:back,class: "btn btn-primary btn-xs"